name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
      - "!**-alpha**"
      - "!**-beta**"

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # "GITHUB_TOKEN" is a secret always provided to the workflow

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Hack around https://github.com/actions/checkout/issues/290
        run: |
          git fetch --tags --force

      - name: Generate Changelog
        run: ./generate_changelog.sh

      - name: Update Build Date
        run: sed -i "s/@build-time@/`date +%Y%m%d%H%M%S`/" WeakAuras/Init.lua

      - name: Flag Non-Experimental Build
        run: |
          sed -i \
          -e "s/--@experimental@/--\[=====\[@experimental@/" \
          -e "s/--@end-experimental@/--@end-experimental@\]=====\]/" WeakAuras/Init.lua

      - name: Create Package
        uses: BigWigsMods/packager@v2
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
